### ISSUE TITLE
boundary_conditions are no longer an attribute of problem class in Dedalus

### ISSUE THREAD

**Issue by evanhanders** [DedalusProject/eigentools#1]
After this commit (https://bitbucket.org/dedalus-project/dedalus/commits/befc23584fea1a0c9c6a33ceb14203bd2c9eea53), the hi-res solve in Eigenproblem fails due to the boundary_conditions attribute of the Problem class being removed.

The simplest solution seems to be to remove lines 167-169 of eigenproblem.py for the newest version of Dedalus, but I might be missing a subtlety.

**Comment by jsoishi** [comment]
Thanks for reporting, Evan. I had fixed this but the changeset didn't make the jump from bitbucket. Fixed in commit 630d17c7a69356bb9c34419bb6ddfb13d154176d.
