### ISSUE TITLE
Can't run first example

### ISSUE THREAD

**Issue by ketch** [DedalusProject/eigentools#6]
I followed the installation instructions and can successfully import both eigentool and dedalus.  However, running the example at https://eigentools.readthedocs.io/en/latest/pages/getting_started.html gives the following:

```
» python temp.py
2021-03-17 11:18:56,937 problems 0/1 INFO :: Solving EVP with homogeneity tolerance of 1.000e-10
Traceback (most recent call last):
  File "temp.py", line 15, in <module>
    EP.solve(sparse=False)
TypeError: solve() got an unexpected keyword argument 'sparse'
```

**Comment by jsoishi** [comment]
hi @ketch, 

Thanks for catching this! It happened because we were waiting on the JOSS refereeing process before releasing this version of eigentools, so the version installed by `pip` is not in line with the documentation. I've created a release candidate associated with this release on PyPI. If it's not against the JOSS reviewing standards, could you try upgrading to this release candidate for the reviewing process? 
You can do so via `pip install eigentools==2.2105rc1`

If JOSS requires the current version, I will do a release right now.

**Comment by ketch** [comment]
@jsoishi I just now cloned the current version of the repository and re-ran the tests.  I don't get the error I saw before, but I do get the following:

```
» python3 temp.py
2021-04-05 13:56:24,742 problems 0/1 INFO :: Solving EVP with homogeneity tolerance of 1.000e-10
2021-04-05 13:56:24,747 problems 0/1 INFO :: Solving EVP with homogeneity tolerance of 1.000e-10
/Users/ketch/Research/Software/eigentools/eigentools/eigenproblem.py:699: RuntimeWarning: divide by zero encountered in true_divide
  inverse_drift = 1/self.delta_near
there are 68 good eigenvalues.
/Users/ketch/Research/Software/eigentools/eigentools/eigenproblem.py:729: RuntimeWarning: divide by zero encountered in true_divide
  ax.semilogy(mode_numbers,1/self.delta_near,'o',alpha=0.4)
/Users/ketch/Research/Software/eigentools/eigentools/eigenproblem.py:730: RuntimeWarning: divide by zero encountered in true_divide
  ax.semilogy(mode_numbers,1/self.delta_ordinal,'x',alpha=0.4)
/Users/ketch/Research/Software/eigentools/eigentools/eigenproblem.py:733: RuntimeWarning: divide by zero encountered in true_divide
  good_near = 1/self.delta_near > self.drift_threshold
/Users/ketch/Research/Software/eigentools/eigentools/eigenproblem.py:734: RuntimeWarning: divide by zero encountered in true_divide
  good_ordinal = 1/self.delta_ordinal > self.drift_threshold
/Users/ketch/Research/Software/eigentools/eigentools/eigenproblem.py:735: RuntimeWarning: divide by zero encountered in true_divide
  ax.semilogy(mode_numbers[good_near],1/self.delta_near[good_near],'o', label='nearest')
/Users/ketch/Research/Software/eigentools/eigentools/eigenproblem.py:736: RuntimeWarning: divide by zero encountered in true_divide
  ax.semilogy(mode_numbers[good_ordinal],1/self.delta_ordinal[good_ordinal],'x',label='ordinal')
```

As far as I can tell, no test failed, but should I be getting these warnings?

**Comment by jsoishi** [comment]
Hi @ketch could you try it with the latest release? This issue is not manifesting for me now.

**Comment by ketch** [comment]
I don't have easy access to an environment where I can test this right now.  If it's working correctly for you, you can close this.
